name: change_package_name
description: "Change Package Name with single command. Update AndroidManifest, build.gradle, MainActivity files & move MainActivity file to new directory structure automatically."
version: 1.0.0
homepage: https://nocorps.org
repository: https://github.com/KANAGARAJ-M/change_package_name
issue_tracker: https://github.com/KANAGARAJ-M/change_package_name/issues

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

  